Updating tests and CI to .Net 7 - Backport Release 6.6
Particular/NServiceBus.Persistence.Sql pull request #1099
Opened 2022-12-08 13:57 UTC by tmasternak

2022-12-08 23:14 UTC, jpalac approved these changes

2022-12-09 01:08 UTC, abparticular requested changes

2022-12-09 01:08 UTC, abparticular commented on .github/workflows/release.yml
> +            7.0.x
```suggestion
          dotnet-version: 7.0.x
```

2022-12-09 03:18 UTC, abparticular approved these changes

2022-12-09 03:30 UTC, merged